name: MSBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}} 
          
      - name: Set the value
        run: |
            echo "VERSION_FILENAME=3_25_${env:BUILD_NUMBER}_0" | Out-File -FilePath $env:GITHUB_ENV -Append
            echo "VERSION_DOT_FILENAME=3.25.${env:BUILD_NUMBER}.0" | Out-File -FilePath $env:GITHUB_ENV -Append
            
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Build
        run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64
        
      - name: Set Versions
        run: |
            DittoSetup\rcedit-x64 Release64\Ditto.exe --set-file-version ${{env.VERSION_DOT_FILENAME}} --set-product-version ${{env.VERSION_DOT_FILENAME}}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          retention-days: 7
          path: |
            Release64\Ditto.exe
            Release64\ICU_Loader.dll
            Release64\Addins\DittoUtil.dll

      - name: Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: DittoSetup\DittoSetup_10.iss

      - name: Build Portable
        run: |
            DittoSetup\BuildPortableZIP.bat "DittoPortable_${{env.VERSION_FILENAME}}" bit64
            
      - name: Zip Debug Files
        run: |
            7z a DittoSetup\output\DittoDebug_${{env.VERSION_FILENAME}}.7z *.pdb -r
            7z a DittoSetup\output\DittoDebug_${{env.VERSION_FILENAME}}.7z *.map -r
            
      - name: Publish to GitHub
        env:
          token: ${{secrets.GITHUB_TOKEN}}
          uploadPath: DittoSetup\output\
          tag: ${{env.VERSION_FILENAME}}
          previous_tag: 3.25.113.0
        run: |
             npm install ./DittoSetup/GitHubRelease
             node ./DittoSetup/GitHubRelease/index.js

